# Generated by Django 5.1.4 on 2025-03-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Performance', '0003_customeruser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='is_superuser',
        ),
    ]
