# Generated by Django 5.1.4 on 2025-03-25 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Performance', '0005_customeruser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique_ext',
            name='ext_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technique_ext',
            name='ext_clients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technique_ext',
            name='ext_intervenant',
            field=models.ManyToManyField(blank=True, null=True, related_name='techniques_externes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technique_ext',
            name='ext_paiement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technique_ext',
            name='ext_remarque',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technique_ext',
            name='ext_resultats',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technique_ext',
            name='ext_statuts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technique_int',
            name='int_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technique_int',
            name='int_clients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technique_int',
            name='int_intervenant',
            field=models.ManyToManyField(blank=True, null=True, related_name='techniques_internes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technique_int',
            name='int_paiement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technique_int',
            name='int_remarque',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technique_int',
            name='int_resultats',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technique_int',
            name='int_statuts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
