# Generated by Django 5.1.4 on 2025-03-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Performance', '0006_alter_technique_ext_ext_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='champ_deux',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technique',
            name='champ_quatre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technique',
            name='champ_trois',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technique',
            name='champ_un',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technique',
            name='liste',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technique',
            name='Facturation_Paiement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facturation_Paiement'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='Facturation_Paiement_externe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facturation_Paiement'),
        ),
    ]
