# Generated by Django 5.1.4 on 2025-03-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Performance', '0007_technique_champ_deux_technique_champ_quatre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boncomtoir',
            old_name='motif_quantite_importer_flyers',
            new_name='pourcentage_individuel_quantite_importer_flyers',
        ),
        migrations.RenameField(
            model_name='boncomtoir',
            old_name='motif_quantite_importer_importer',
            new_name='pourcentage_individuel_quantite_importer_importer',
        ),
        migrations.RenameField(
            model_name='boncomtoir',
            old_name='motif_quantite_produit',
            new_name='pourcentage_individuel_quantite_produit',
        ),
        migrations.RenameField(
            model_name='subcomptoir',
            old_name='motif',
            new_name='pourcentage_individuel',
        ),
    ]
