# Generated by Django 5.1.4 on 2025-03-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Performance', '0009_rename_pourcentage_individuel_subcomptoir_pourcentage_de_charge_individuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncomtoir',
            name='objectif_quantite_importer_flyers',
        ),
        migrations.RemoveField(
            model_name='boncomtoir',
            name='objectif_quantite_importer_importer',
        ),
        migrations.RemoveField(
            model_name='boncomtoir',
            name='objectif_quantite_produit',
        ),
        migrations.RemoveField(
            model_name='subcomptoir',
            name='objectif',
        ),
    ]
